### ISSUE TITLE
Do you need a hand?

### ISSUE THREAD

**Issue by lqmanh** [supabase/postgrest-py#1]
Hello,

I find this repo was created for some time but hasn't had anything yet. Therefore, I decided to roll out my own version of PostgREST client for Python [here (lqmanh/postgrest_py)](https://github.com/lqmanh/postgrest_py). It's heavily inspired by both _postgrest-js_ and _postgrest-rs_ with nearly indentical API.
There are some missing features and no documentation yet, but it work already.
I think I can continue developing this library, if you guys need some help.

**Comment by awalias** [comment]
hey @lqmanh !

Nice work on the lib, we would love to join forces here if you are keen as at some point we will be implementing a supabase-py which will need to wrap postgrest_py, I'm personally a huge fan of flask so would love to hack on some python web apps w/supabase+postgrest

**Comment by lqmanh** [comment]
Thank you @awalias,

My lib is still at very early stage of development. It lacks features, input validating, tests, docs,... and may be buggy. Feel free to fire issues or create PRs. I'm open to every possible help and suggestions.
And I'd love to help Supabase with supabase-py, if that's ok.
