### ISSUE TITLE
#461 broke the like operator when special characters are used `,:()`

### ISSUE THREAD

**Issue by Sandr0x00** [supabase/postgrest-py#477]
# Bug report

## Describe the bug

Before the change in #461, the "like" query was built like this with `:value%`

```
like.%3Avalue%25
```

Since the change, it is built like this:

```
like.%22%3Avalue%2A%22
```

The reason is the called `pattern = sanitize_pattern_param(pattern)` which surrounds the value with `"` whenever a "special" character `,:()` is in the request.

Using `"` around the value will result in an empty set to be returned instead of the actual data matching `:value%`.

## To Reproduce

Do a select query with 

```
.like("column", ":value%")
```

and check the result returned from the database.

## Expected behavior

Using the like operator and get values in return

**Comment by silentworks** [comment]
Please provide concrete examples when you are supplying steps to reproduce an issue. `column` and `value` aren't concrete examples, they are very abstract.

**Comment by Sandr0x00** [comment]
Well, the bug is universal and triggers in any case explained, but sure. Create a table like

```sql
CREATE TABLE tbl
(
    id int PRIMARY KEY generated always as identity,
    col text
);

INSERT INTO tbl
    (col)
VALUES
    ('http://web.site'),
    ('https://web.page'),
    ('http://google.com'),
    ('https://github.com');
```

and execute the following script (I use the supabase-client since it's a convenient wrapper for me, but it's just a wrapper around postgrest.

```py
import logging
import os
from supabase import create_client
from postgrest import SyncRequestBuilder

# logging to see the httpx request created
logging.basicConfig(
    level=logging.INFO
)

# supabase wrapper
client = create_client(
    os.getenv("SUPABASE_URL"),
    os.getenv("SUPABASE_SERVICE_ROLE_KEY")
)
req_builder: SyncRequestBuilder = client.table("tbl")

# from here on, only postgrest functions
data = req_builder.select("*").like("col", "https://%").execute().data
print(data)
```
