### ISSUE TITLE
select() does not select all columns by default

### ISSUE THREAD

**Issue by 9t8** [supabase/postgrest-py#507]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

[The docs](https://supabase.com/docs/reference/python/select) say the `columns` parameter of `select()` "defaults to `*`." It does not.

## To Reproduce

1. Run `supabase.table("t").select("*")`, and get everything in `t`.
2. Run `supabase.table("t").select("")`, and get everything in `t`.
3. Run `supabase.table("t").select()`, and get no data.

## Expected behavior

`supabase.table("t").select()` should get everything in `t`. I understand "defaults to `*`" to mean `*` is the default argument.

**Comment by grdsdev** [comment]
Hi, thanks for reporting this.

Behavior should be aligned between client libs, `select()` without arguments should default to `*` all columns.

If you need to use `HEAD` method, you can specify `head=True` when calling the select method ([just like JS](https://github.com/supabase/postgrest-js/blob/master/src/PostgrestQueryBuilder.ts#L63)), at least this should be the behavior in Python too.

From what I see, this isn't supported as expected.

---

This fix would be a breaking change, tho currently it has the wrong behavior, @silentworks what do you think about this?

**Comment by silentworks** [comment]
I think we should apply the breaking change since this is a bug fix, the current behavior is a bug. We should probably do a minor release and not a patch release for this though.

**Comment by grdsdev** [comment]
Agreed, I'll push a PR with the fix.
