### ISSUE TITLE
Сonfusion with minimal Python version

### ISSUE THREAD

**Issue by danfimov** [supabase/postgrest-py#517]
# Chore

## Describe the chore

Different parts of the project specify different minimum python versions:

- In the project's README.md `^3.9`
- In badges in README.md - `3.8 | 3.9 ...`
- In documentation `^3.7`
- In CI tests run with `^3.9`
- In `pyproject.toml` the version is `^3.8`

I consider the source of truth is `pyproject.toml`, so I think it would be great to bring these places to a unified form:

- Put Python version `>=3.8` in the documentation
- Start running tests with version `3.8`

**Comment by silentworks** [comment]
The minimal version this project supports is 3.9. Please refer to the Python docs about supported versions of Python. https://devguide.python.org/versions/

**Comment by silentworks** [comment]
I've updated the readme and the `pyproject.toml` to reflect the support from 3.9 upwards.
