### ISSUE TITLE
Install strenum package only with Python 3.10 and older

### ISSUE THREAD

**Issue by danfimov** [supabase/postgrest-py#518]
# Chore

## Describe the chore

There is no need to install the `strenum` package if the user of the library uses Python 3.11 or later. Therefore, I would like to add an additional restriction on this dependency and not install it on fresh versions of Python.

## Additional context

The only place where `strenum` package is used is [here](https://github.com/supabase/postgrest-py/blob/a8aee9a7f5a708eb5f6622a3388ebbf302d530b5/postgrest/types.py#L8)

```
import sys

if sys.version_info >= (3, 11):
    from enum import StrEnum
else:
    from strenum import StrEnum
```

`StrEnum` [added](https://docs.python.org/3/whatsnew/3.11.html#enum) in standard `enum` library since Python 3.11.

**Comment by silentworks** [comment]
Thanks for the PR. This was merged in and will be available in the next release.
